algoritmo "semnome"
// Função :
// Autor :
// Data : 24/02/2022
// Seção de Declarações 
Var
clube: caracter


Inicio
escreva ("Digite um clube de sp e rj")
leia (clube)
escolha (clube)
caso "Palmeiras", "Corinthians", "Santos", "São Paulo"
 escreva ("Clube de SP")
caso "Fluminense", "Flamengo", "Botafogo", "Vasco"
 escreva ("Clube do RJ")
outrocaso
 escreva ("Clube de outro estado, ou desconhecido")

fimescolha


Fimalgoritmo
