algoritmo "semnome"
// Função :
// Autor :
// Data : 07/03/2022
// Seção de Declarações 
var
//Nas linguagens de programação, o índice começa com 0
filmes: vetor [0..4] de caractere
indice, ordem: inteiro

inicio
para indice de 0 ate 4 faca
escreval("Informe seus números favoritos")
 leia (filmes [indice])
fimpara


ordem <- 1
para indice de 0 ate 4 faca
 escreval (ordem,"ºfime:",filmes[indice])
  ordem<-ordem+1
fimpara
fimalgoritmo
