algoritmo "semnome"
// Função :
// Autor :
// Data : 24/02/2022
// Seção de Declarações 
var
linhainserida:caracter
inicio
escreva ("Digite o código da linha de ônibus:")
leia(linhainserida)
se (linhainserida = "2019") ou (linhainserida = "2023") entao
escreva ("A linha ", linhainserida, " passa pelo SENAC PENHA")
senao
escreva ("A linha ", linhainserida, " não passa pelo SENAC PENHA")

fimse

fimalgoritmo
