algoritmo "semnome"
// Função :
// Autor :
// Data : 24/02/2022
// Seção de Declarações 
var
linhainserida: caracter

inicio
escreva ("Digite o código da linha de ônibus:")
leia (linhainserida)
escolha (linhainserida)
 caso "2019","2203"
   escreva ("A linha CÓDIGO_DA_LINHA passa pelo Senac Penha")
 outrocaso
   escreva ("A linha CÓDIGO_DA_LINHA não passa pelo Senac Penha")
   
fimescolha

fimalgoritmo
